services:
  work-log-web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - work-log-php-fpm
    ports:
      - '${APP_PORT:-80}:80'
    restart: unless-stopped

  # Runs the backend PHP server
  work-log-php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      work-log-pgsql:
        condition: service_healthy
      work-log-redis:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  work-log-pgsql:
    image: postgres:17.5-alpine3.22
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - work-log-postgres-data-production:/var/lib/postgres-data

  work-log-redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  work-log-postgres-data-production:

