apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-log-web
  labels:
    app.kubernetes.io/name: work-log
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: work-log
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: work-log
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: work-log
  template:
    metadata:
      labels:
        app.kubernetes.io/name: work-log
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: work-log
    spec:
      containers:
        - name: web
          image: harbor.eyanje.net/work-log/web:latest
          ports:
            - containerPort: 80
              name: http

