apiVersion: v1
kind: Service
metadata:
  name: work-log-redis
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: work-log
    app.kubernetes.io/part-of: work-log
spec:
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: work-log
    app.kubernetes.io/part-of: work-log
  ports:
    - port: 6379
      targetPort: 6379

