apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: work-log-redis
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: work-log
    app.kubernetes.io/part-of: work-log
spec:
  serviceName: work-log-redis
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: work-log
      app.kubernetes.io/part-of: work-log
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        app.kubernetes.io/name: work-log
        app.kubernetes.io/part-of: work-log
    spec:
      containers:
        - image: docker.io/redis:latest
          livenessProbe:
            tcpSocket:
              port: 6379
          name: redis
          readinessProbe:
            tcpSocket:
              port: 6379
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/component: redis
          app.kubernetes.io/name: work-log
          app.kubernetes.io/part-of: work-log
      spec:
        accessModes: ["ReadWriteOncePod"]
        resources:
          requests:
            storage: 1Gi

