---
apiVersion: v1
kind: ConfigMap
metadata:
  name: work-log-environment-config
  labels:
    app.kubernetes.io/name: work-log
    app.kubernetes.io/part-of: work-log
data:
  APP_NAME: "Journal"
  APP_ENV: "local"
  APP_DEBUG: "false"
  APP_URL: "https://journal.eyanje.net"

  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"

  PHP_CLI_SERVER_WORKERS: "4"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "pgsql"

  DB_HOST: "work-log-pgsql"
  DB_PORT: "5432"
  DB_DATABASE: "laravel"
  DB_USERNAME: "root"


  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"

  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: "database"

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: "6379"

  MAIL_MAILER: "log"
  MAIL_HOST: "127.0.0.1"
  MAIL_PORT: "2525"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_DEFAULT_REGION: "us-east-1"
  AWS_USE_PATH_STYLE_ENDPOINT: "false"


  VITE_APP_NAME: "Journal"
...
